Repository Mentro-Org/Mentro-Community-Blog, pull requests merged in 2021-10, with the labels that each got.

#19 ashusengar -> Updated clone and cd command
  README.md
Labels: enhancement, Hacktoberfest2021, Hacktoberfest-accepted

#22 added auto-commenter
  .github/workflows/auto-comment.yml
Labels: enhancement, good first issue, Hacktoberfest2021

#23 Enhancement of Website
  assets/css/main.css
Labels: enhancement, good first issue, frontend, Hacktoberfest2021

#34 I Desgined the thumbnail for Getting Started with API
  assets/images/thumbnails/Getting Started with API.png
Labels: Hacktoberfest2021, design

#29 Updated dependency versions and fixed some errors in css file
  assets/css/main.css
Labels: enhancement, help wanted, Hacktoberfest2021
